Added Polish locale (actually good)
pindab0ter/UPSFriendlyNixieTubeDisplay pull request #2
Opened 2024-11-25 01:33 UTC by skill3472

Added Polish translation. The other PR has a typo, so please don't accept #1

2024-11-25 07:00 UTC, pindab0ter requested changes
FYI, you can fix things with a new commit and push it to he same branch, this will update the PR so you don't have to make a new one for every change.

2024-11-25 07:00 UTC, pindab0ter commented on locale/en/pl.cfg
> +classic-nixie-tube=Lampa Jarzeniowa
Do you think "[Lampa cyfrowa](https://pl.wikipedia.org/wiki/Lampa_cyfrowa)" is a better translation? Apparently "Jarzeniowa" is "fluorescent lamp", which a Nixie tube is not.

2024-11-25 08:45 UTC, pindab0ter commented
Your PR inspired me to improve the localisation and add Dutch as well. Please review the changes to the [`en.cfg`](https://github.com/pindab0ter/UPSFriendlyNixieTubeDisplay/commit/8c182590d0432ab9fd9eb71b81c33138b42601b3) file.

2024-11-25 11:52 UTC, skill3472 commented
Hey, the full name for a nixie tube is Jarzeniowa Lampa Cyfrowa, so that's
just a shortening we use in common language - I think it's more descriptive
here, than the other options for a nixie tube that I checked. I also
verified this with 2 of my friends, we think it's the best translation :)
But it's your fork, if you wanna change it, you can!
---
Maksymilian Tym

pon., 25 lis 2024, 09:45 użytkownik Hans van Luttikhuizen-Ross <
***@***.***> napisał:

> Your PR inspired me to improve the localisation and add Dutch as well.
> Please review the changes to the en.cfg
> <https://github.com/pindab0ter/UPSFriendlyNixieTubeDisplay/commit/8c182590d0432ab9fd9eb71b81c33138b42601b3>
> file.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pindab0ter/UPSFriendlyNixieTubeDisplay/pull/2#issuecomment-2497287798>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG2G3XZX6LCGRIYHY2RRPB32CLPSVAVCNFSM6AAAAABSM3WAGCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJXGI4DONZZHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-25 12:10 UTC, pindab0ter commented
Hey, thank you for your explanation! I was just doing a sanity check. I don't speak Polish, so if you say you and your friends think this is the right translation, then that's good enough for me!

Could you update the translations to match the changes I've made since you created the PR?

2024-11-25 12:11 UTC, pindab0ter requested changes

2024-11-25 12:11 UTC, pindab0ter commented on locale/en/pl.cfg
The file should be in `locale/pl/pl.cfg`, not in `locale/en/pl.cfg`.

2024-11-25 12:13 UTC, pindab0ter requested changes

2024-11-25 12:13 UTC, pindab0ter commented on locale/en/pl.cfg
Please update the translations to match the changes I've made to [`locale/en/en.cfg`](https://github.com/pindab0ter/UPSFriendlyNixieTubeDisplay/blob/34896217418c5f13c1c2bc6495fe1aad0e614233/locale/en/en.cfg)

2024-11-25 12:19 UTC, skill3472 commented on locale/en/pl.cfg
Yessir! I'll do all that after work today, thanks for the tip.

2024-11-26 00:51 UTC, skill3472 commented
Hey there! Back from work, I think everything is up to the new specifications. Please review :)
Cheers!

2024-11-26 08:38 UTC, pindab0ter approved these changes

2024-11-26 08:43 UTC, pindab0ter approved these changes

2024-11-26 08:43 UTC, merged

2024-11-26 10:30 UTC, pindab0ter commented
Thank you for your contribution!

I updated the mod, so you should be able to enjoy your Polish translation now.